name: Build and Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Create ZIP Package
        run: |
          cd publish
          zip -r ../app.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
        id-token: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package


      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_STAGING }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to azure production
        run: |
          az webapp deploy --name app-staging-westeurope --resource-group rg-staging --src-path app.zip --type zip
